#ifndef __CONFIG_ZYNQ_RED_PITAYA_H
#define __CONFIG_ZYNQ_RED_PITAYA_H

#define CONFIG_SYS_SDRAM_SIZE		(480 * 1024 * 1024)

#define CONFIG_ZYNQ_SERIAL_UART0
#define CONFIG_ZYNQ_GEM0
#define CONFIG_ZYNQ_GEM_PHY_ADDR0	1

#define CONFIG_SYS_NO_FLASH

#define CONFIG_ZYNQ_USB
#define CONFIG_ZYNQ_SDHCI0

#define CONFIG_ZYNQ_BOOT_FREEBSD

#include <configs/zynq-common.h>

#undef CONFIG_PHY_MARVELL

#define CONFIG_PHY_LANTIQ

#endif /* __CONFIG_ZYNQ_RED_PITAYA_H */

