package ifneeded vfs        1.4.2  [list load {} vfs]
package ifneeded starkit    1.3.3  [list source [file join $dir starkit.tcl]]
package ifneeded vfslib     1.4    [list source [file join $dir vfslib.tcl]]
package ifneeded vfs::mk4   1.10.1 [list source [file join $dir mk4vfs.tcl]]
package ifneeded vfs::zip   1.0.4  [list source [file join $dir zipvfs.tcl]]
